### ISSUE TITLE
Doesn't assign a technician to a ticket when a ticket is submitted via email

### ISSUE THREAD

**Issue by krzysztofmaciejewskiit** [initiativa/roundrobin#15]
I have a problem because I am configuring GLPI as a new ticketing system for the company I work for, but the tickets are not being assigned to users using the round-robin method.

When the ticket is created from GLPI and when I manually select the category then everything works correct, the ticket goes to my group and the technician is randomly assigned.
When I do it by email from my mail only the main unit is assigned thanks to the rule I posted below.

I don't know how to do this, but maybe you know how to assign categories to tickets submitted by email?

![image](https://github.com/initiativa/roundrobin/assets/128192435/0e7a0369-2985-44d6-8d84-b6ab09e7a6a1)

![image](https://github.com/initiativa/roundrobin/assets/128192435/e89947e7-3a3c-4c88-8db2-5f4fa513b65d)

![image](https://github.com/initiativa/roundrobin/assets/128192435/c10c10ca-43f4-4979-9442-adcab1076e41)

I think the problem may be in the screen shot below (Automatic user assignment), just don't know how I can configure it.
![image](https://github.com/initiativa/roundrobin/assets/128192435/c5890f3f-cd89-4a65-ae51-d833976c9738)

I noticed that when this option is selected, when you create the request yourself and manually select the cateogry, then it all works correctly with assignment to users by round robin method. 
![image](https://github.com/initiativa/roundrobin/assets/128192435/47ef79bf-efa3-4fd8-bcef-82a51d1d3b68)

![image](https://github.com/initiativa/roundrobin/assets/128192435/023d8b6b-b2e9-4f0f-9485-1fe3d42ffec6)

**Comment by krzysztofmaciejewskiit** [comment]
Does anyone have an idea how to solve my problem with assigning tickets to a group when the ticket is submitted via email?

**Comment by JohnRossZA** [comment]
@krzysztofmaciejewskiit How does your Business Rules look like, you need to setup a rule, to have Category assigned.

**Comment by mlegend82** [comment]
I found how to solve it:

For those using the marketplace plugin, go to glpi/marketplace/roundrobin/inc/ and edit the file TicketHookHandler.class.php. On line 136, replace WHERE tickets_id = {$ticketId}; with WHERE tickets_id = {$ticketId} AND type = 2;.

Funny enough, I found the file right here in this repository, haha.

If you're not using the marketplace, just go to the /glpi/plugins directory."
