### ISSUE TITLE
RoundRobin Settings dont show ITIL Category

### ISSUE THREAD

**Issue by grcmec** [initiativa/roundrobin#2]
Hello.
Than you for your help, with the update I can install the pluging, but, in the cconfiguration page I can't see any ITIL category, for yoour control I did it:
1. Install the plugin
2. Activate it
3. In the RoundRobing settings page I select yes and save
4. I create a glpi group and create some users with the technician profile
5. In each ITIL categories I add this group in Group in Charge of the Hardware

In the ReoundRobin Settings page I can't see the information of the ITIL Category - Group - Member # and Setting, and of course the plugin don't assing the roundrobin users.
I appreciate you help

**Comment by grcmec** [comment]
I create a new ITIL category item and it appear in the RoundRobing Settings page, only the previus ITIL category items created don't show on it.

**Comment by Giudy** [comment]
Strange, which version of GLPi are you using? 
Round robin should show all the categories with the field "group in charge of the hardware" set to a Group.
The ITIL categories listed can be created before or after the setup of the plugin, it doesn't matter.
here an example. can you do a new check?

![image](https://user-images.githubusercontent.com/7987648/155404593-06e2314b-782d-43e9-aaa1-9abcc1319c41.png)

**Comment by grcmec** [comment]
Hi, I have some items in the ITIL Categories, and the in the configuration page I see only one of this, I check the database and add manually the link of Estado de Cuenta de Clientes
![image](https://user-images.githubusercontent.com/28117868/155405744-9fa74b57-99af-41b0-84d9-e3ea287ef4b5.png)

![image](https://user-images.githubusercontent.com/28117868/155405922-8fb32aa0-fec5-417e-89c2-a11998a60856.png)

**Comment by Giudy** [comment]
mmmm .. cannot reproduce.
How do add manually the link?

**Comment by Giudy** [comment]
does it change if you set to NO the "assign also to the original group"? radio button?

**Comment by grcmec** [comment]
> I add new record on the table glpi_plugin_roundrobin_rr_assignments, the las row was created automatically with the las itil category created
![image](https://user-images.githubusercontent.com/28117868/155412077-774c6664-910e-49c7-830f-94e1ea8a1726.png)

**Comment by Giudy** [comment]
Perfect, thankyou. 
We will try to understand which is the case.

**Comment by grcmec** [comment]
> Perfect, thankyou. We will try to understand which is the case.
If you need more information, please let me know.

**Comment by grcmec** [comment]
> Perfect, thankyou. We will try to understand which is the case.

This is the table ITILcategories
![image](https://user-images.githubusercontent.com/28117868/155413434-8c0b9c7b-4b84-4fa0-8d38-6ae7240a1a4e.png)

**Comment by intruder64** [comment]
Greetings grcmec,

Great. We have not produced a new release, yet, but we appreciate your positive feedbacks.

Thanks.
All the best.

**Comment by Giudy** [comment]
Ok, new release created. 
thank you for your support!
