### ISSUE TITLE
Unable to install on GLPI 9.5.2

### ISSUE THREAD

**Issue by grcmec** [initiativa/roundrobin#3]
Hi.
I try to install on GLPI 9.5.2, but I can do it.
![image](https://user-images.githubusercontent.com/28117868/155561697-51f5ac6d-7c5d-48d2-af9e-961dcbfa39fb.png)

**Comment by Giudy** [comment]
Sorry, true. we were wrong in defining the plugin compatible with glpi prior to glpi v 9.5.5. we'll change the compatibility according to this.
