### ISSUE TITLE
When apply roundrobin plugin in GLPI 10.0.0 not requester in selfservice

### ISSUE THREAD

**Issue by cmoreno038** [initiativa/roundrobin#8]
When open a ticket with plugin applied on ITIL category (INFRAESTRUCTURA) does not show a requester in new ticket
![imagen](https://user-images.githubusercontent.com/44004531/170155446-f2e204e1-d370-480b-bf22-bf809a63d121.png)
![imagen](https://user-images.githubusercontent.com/44004531/170155638-befd418a-974f-4318-a705-2b843ed05afa.png)
![imagen](https://user-images.githubusercontent.com/44004531/170155721-24ba70ad-bfe8-41c4-ba2a-683bdc16836b.png)

When I already deactivated the requester show in the ticket
![imagen](https://user-images.githubusercontent.com/44004531/170155872-15d31836-6ebb-4efa-94dc-bad1b0a25b57.png)
![imagen](https://user-images.githubusercontent.com/44004531/170155950-6fd94d7f-fa12-447e-9f09-bfedba3d10d6.png)
![imagen](https://user-images.githubusercontent.com/44004531/170155997-1e26e67b-a3a6-415f-973c-bcae48bb2ec4.png)
![imagen](https://user-images.githubusercontent.com/44004531/170156058-68c471c6-6efc-47ed-9832-eee15e55829a.png)

**Comment by gabrielhaasee** [comment]
hello, how much with the same incident in glpi 10.0.0.
When entering a new request, it deletes the requestor.

**Comment by cmoreno038** [comment]
With the following issue it solve his
https://github.com/initiativa/roundrobin/pull/7
